{% set name = "python-vagrant" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a8fe93ccf2ff37ecc95ec2f49ea74a91a6ce73a4db4a16a98dd26d397cfd09e5

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - vagrant

about:
  home: https://github.com/todddeluca/python-vagrant
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python bindings for interacting with Vagrant virtual machines.

extra:
  recipe-maintainers:
    - pg-hbk
    - sy-hbk
